=== M0nizar/xml_tps/td3/exo3/exo3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
 
    <!--first contraint-->
    <xs:simpleType name="ISBN">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][0-9]{10}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--second contraint-->
    <xs:simpleType name="titreType">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--third contraint-->
    <xs:simpleType name="genreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Scientifique"></xs:enumeration>
            <xs:enumeration value="Roman"></xs:enumeration>
            <xs:enumeration value="Science-Fiction"></xs:enumeration>
            <xs:enumeration value="Histoire"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <!--fourth contraint-->
    <xs:simpleType name="langueType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]{2}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    
    <!--fifth contraint-->
    <xs:simpleType name="prixType">
        <xs:restriction base="xs:decimal">
            <xs:maxExclusive value="10000"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
 
    <!--sixth contraint-->
    <xs:simpleType name="dateType">
        <xs:restriction base="xs:gYear">
            <xs:minExclusive value="1800"/>
            <xs:maxExclusive value="2025"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--seventh contraint-->
    <xs:simpleType name="pageType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+Ã [0-9]+"/>
        </xs:restriction>
    </xs:simpleType>
 
 <xs:element name="bibliotheque">
     <xs:complexType>
         <xs:sequence>
             <xs:element name="livre" maxOccurs="unbounded">
                 <xs:complexType>
                     <xs:sequence>
                         <xs:element name="titre" type="titreType"/>
                         <xs:element name="genre" type="genreType" default="Scientifique"/>   
                         <xs:element name="langue" type="langueType"/>
                         <xs:element name="prix" type="prixType"/>
                         <xs:element name="resume" type="xs:string" minOccurs="0"/>
                         <xs:element name="annee_de_publication" type="dateType"/>
                         <xs:element name="chapitres" >
                             <xs:complexType>
                                 <xs:sequence>
                                     <xs:element name="chapitre" maxOccurs="unbounded">
                                         <xs:complexType>
                                             <xs:sequence>
                                                 <xs:element name="titre" type="xs:string"/>
                                                 <xs:element name="sousTitre" type="xs:string" minOccurs="0"/>
                                                 <xs:element name="nombre_page" type="pageType"/>
                                             </xs:sequence>
                                         </xs:complexType>
                                     </xs:element>
                                 </xs:sequence>
                             </xs:complexType>
                         </xs:element>
                     </xs:sequence>
                     <xs:attribute name="id" type="ISBN" use="required"/> 
                 </xs:complexType>
             </xs:element>
                    
         </xs:sequence>
        
     </xs:complexType>
 </xs:element>
    
</xs:schema>

=== M0nizar/xml_tps/td3/exo3/exo3.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliotheque 
    xmlns="http://www.example.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.com exo3.xsd">
    
    <livre id="C2025345678">
        <titre>L'apprentissage XML</titre>
        <genre>Scientifique</genre>
        <langue>fr</langue>
        <prix>49.99</prix>
        <resume>Cet ouvrage explique les bases du XML et son utilisation dans le web moderne.</resume>
        <annee_de_publication>2023</annee_de_publication>
        
        <chapitres>
            <chapitre>
                <titre>Introduction à XML</titre>
                <sousTitre>Notions de base</sousTitre>
                <nombre_page>1à10</nombre_page>
            </chapitre>
            <chapitre>
                <titre>Validation avec XSD</titre>
                <nombre_page>11à20</nombre_page>
            </chapitre>
        </chapitres>
    </livre>
    
    <livre id="C2325345678">
        <titre>Histoire des Sciences</titre>
        <genre>Histoire</genre>
        <langue>en</langue>
        <prix>59.95</prix>
        <annee_de_publication>2021</annee_de_publication>
        
        <chapitres>
            <chapitre>
                <titre>Les débuts de la science</titre>
                <nombre_page>1à15</nombre_page>
            </chapitre>
            <chapitre>
                <titre>L'ère moderne</titre>
                <sousTitre>Révolutions scientifiques</sousTitre>
                <nombre_page>16à30</nombre_page>
            </chapitre>
        </chapitres>
    </livre>
    
</bibliotheque>
