=== M0nizar/xml_tps/td3/exo1/exo1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"

    elementFormDefault="qualified">
    
    <xs:element name="etablissements">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="universite" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="annee_fondation" type="xs:gYear"/>
                            <xs:element name="faculte" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom" type="xs:string"/>
                                        <xs:element name="doyen" type="xs:string"/>
                                        <xs:element name="departement" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nom" type="xs:string"/>
                                                    <xs:element name="chef_departement" type="xs:string"/>
                                                    <xs:element name="enseignants">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="enseignant" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="nom" type="xs:string"/>
                                                                            <xs:element name="prenom" type="xs:string"/>
                                                                            <xs:element name="date_naissance" type="xs:date"/>
                                                                            <xs:element name="specialite" type="xs:string"/>
                                                                            <xs:element name="enseignements">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="matiÃ¨re" maxOccurs="unbounded">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element name="titre" type="xs:string"/>
                                                                                                    <xs:element name="credits" type="xs:int"/>
                                                                                                </xs:sequence>
                                                                                                <xs:attribute name="code" type="xs:string" use="required"/>
                                                                                                <xs:attribute name="type" type="xs:string" use="required"/>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="id" type="xs:string" use="required"/>
                                                                        <xs:attribute name="grade" type="xs:string" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== M0nizar/xml_tps/td3/exo1/exo1.xml
<?xml version="1.0" encoding="UTF-8"?>

<etablissements xmlns="http://www.example.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.com exo1.xsd">
<universite>
    <nom>Université de Sidi Bel Abbes</nom>
    <annee_fondation>1978</annee_fondation>
    <faculte>
        <nom>Sciences Exactes</nom>
        <doyen>Attouch Mohammed</doyen>
        <departement>
            <nom>Informatique</nom>
            <chef_departement>Benali Youcef</chef_departement>
            <enseignants>
                <enseignant id="ENS001" grade="MCA">
                    <nom>Ammar</nom>
                    <prenom>Réda</prenom>
                    <date_naissance>1958-09-30</date_naissance>
                    <specialite>Intelligence Artificielle</specialite>
                    <enseignements>
                        <matière code="INF101" type="cours">
                            <titre>Intelligence Artificielle avancée</titre>
                            <credits>6</credits>
                        </matière>
                        <matière code="INF302" type="TP">
                            <titre>Introduction à la programmation Python</titre>
                            <credits>3</credits>
                        </matière>
                    </enseignements>
                </enseignant>
                <!--Autres enseignants -->
            </enseignants>
        </departement>
        <!--Autres départements -->
    </faculte>
    <!--Autres facultés -->
</universite>
<!--Autres etablissements -->
</etablissements>
